Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
-------------------------
 Before deleting largest 
-------------------------

      -5
      / \
     /   \
    -6   -1
   /     /
  -7    -2
 /     /
-8    -3
     /
    -4

------------------------
 After deleting largest 
------------------------

      -5
      / \
     /   \
    -6   -2
   /     /
  -7    -3
 /     /
-8    -4

Deleted value: -1
