Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
--------------------------
 Before doubling the tree 
--------------------------

    3
   / \
  2   4
 /     \
1       5

-------------------------
 After doubling the tree 
-------------------------

          3
         / \
        3   4
       /   / \
      2   4   5
     /       /
    2       5
   /
  1
 /
1

