Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
--------------------------
 Before doubling the tree 
--------------------------

      4
     / \
    /   \
   /     \
  2       6
 / \     / \
1   3   5   7

-------------------------
 After doubling the tree 
-------------------------

            4
           / \
          /   \
         /     \
        4       6
       /       / \
      2       6   7
     / \     /   /
    2   3   5   7
   /   /   /
  1   3   5
 /
1

