Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: Enter val1: Enter val2: 
Tree:

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

val1: 3
val2: 5

bstLowestCommonAncestor returned: 4
