Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: Enter min: Enter max: 
-----------------
 Before trimming 
-----------------

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

min: 7
max: 9

----------------
 After trimming 
----------------

  8
 / \
7   9

