Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: Enter min: Enter max: 
-----------------
 Before trimming 
-----------------

   10
   / \
  /   \
 /     \
1      19
 \     /
  9   11
 /     \
2      18
 \     /
  8   12
 /     \
3      17
 \     /
  7   13
 /     \
4      16
 \     /
  6   14
 /     \
5      15

min: 6
max: 14

----------------
 After trimming 
----------------

        10
        / \
       /   \
      9    11
     /       \
    8        12
   /           \
  7            13
 /               \
6                14

