Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
Tree:

           10
           / \
          /   \
         /     \
        /       \
       /         \
      9          11
     /             \
    8              12
   /                 \
  2                  18
 / \                 / \
1   3               /   \
     \             17   19
      4           /
       \         16
        6       /
       / \     14
      5   7   / \
             /   \
            13   15

treeNumInternal returned: 13
