Enter the preorder traversal of tree 1: Enter the in-order traversal of tree 1: Enter the preorder traversal of tree 2: Enter the in-order traversal of tree 2: 
Tree 1:

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              13
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       11     15
 / \     / \     / \     / \
1   3   5   7   9  12   /   \
                       14   16

Tree 2:

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

treeEq returned: FALSE
