Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
------------------------
 Before deleting leaves 
------------------------

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

-----------------------
 After deleting leaves 
-----------------------

      8
     / \
    /   \
   /     \
  4      12
 / \     / \
2   6   /   \
       10   14

