Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
------------------------
 Before deleting leaves 
------------------------

   10
   / \
  /   \
 /     \
1      19
 \     /
  9   11
 /     \
2      18
 \     /
  8   12
 /     \
3      17
 \     /
  7   13
 /     \
4      16
 \     /
  6   14
 /     \
5      15

-----------------------
 After deleting leaves 
-----------------------

   10
   / \
  /   \
 /     \
1      19
 \     /
  9   11
 /     \
2      18
 \     /
  8   12
 /     \
3      17
 \     /
  7   13
 /     \
4      16
 \     /
  6   14

