#!/bin/bash
# Compiles an exercise

COMMON_DIR="common/"
EXERCISES_DIR="exercises/"
SOLUTIONS_DIR="solutions/"
TEST_DRIVERS_DIR="testDrivers/"

usage()
{
	echo "Usage: $0 [-s] <exercise>"
	echo "Options:"
	echo "    -s    compiles the solution instead of your code"
	exit 1
}

check_solutions_exist()
{
	if [ ! -d "$SOLUTIONS_DIR" ]
	then
		echo "$0: No solutions available"
		exit 1
	fi
}

# $1: exercise name
check_exercise_exists()
{
	if [ ! -e "$EXERCISES_DIR/$1.c" ]
	then
		echo "$0: No exercise named '$1'"
		exit 1
	fi
}

# $1: exercise name
check_exercise_solution_exists()
{	
	if [ ! -e "$SOLUTIONS_DIR/$1.c" ]
	then
		echo "$0: No solutions available for $1"
		exit 1
	fi
}

# $1: exercise name
# $2: source directory
compile_test_driver()
{
	check_test_driver_exists "$1"
	gcc -Wall -Werror -std=gnu99 -g -o testList "$COMMON_DIR"/*.[co] "$TEST_DRIVERS_DIR/test${1^}.c" "$2/$1.c" || exit 1
}

# $1: exercise name
check_test_driver_exists()
{
	if [ ! -e "$TEST_DRIVERS_DIR/test${1^}.c" ]
	then
		echo "$0: No test driver available for $1"
		exit 1
	fi
}

########################################################################
# process args

if [ $# -eq 0 -o $# -gt 2 ] || [ $# -eq 2 -a $1 != "-s" ]
then
	usage
fi

if [ $# -eq 1 ]
then
	exercise_name="$1"
	source_dir="$EXERCISES_DIR"
else
	exercise_name="$2"
	source_dir="$SOLUTIONS_DIR"
fi

cd $(dirname $0)

if [ "$source_dir" = "$SOLUTIONS_DIR" ]
then
	check_solutions_exist
fi

########################################################################

check_exercise_exists "$exercise_name"

if [ "$source_dir" = "$SOLUTIONS_DIR" ]
then
	check_exercise_solution_exists "$exercise_name"
fi

compile_test_driver "$exercise_name" "$source_dir"

echo "Compiled successfully! You can now test your $exercise_name function by running ./testList"

