Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
Tree:

              8
             / \
            /   \
           /     \
          /       \
         /         \
        /           \
       /             \
      4              12
     / \             / \
    /   \           /   \
   /     \         /     \
  2       6       10     14
 / \     / \     / \     / \
1   3   5   7   9  11   /   \
                       13   15

Returned array: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
