Enter the preorder traversal of the tree: Enter the in-order traversal of the tree: 
Tree:

    3
   / \
  2   4
 /     \
1       5

Enter sum: sum: 1
treeHasPathSum returned: FALSE

Enter sum: sum: 2
treeHasPathSum returned: FALSE

Enter sum: sum: 3
treeHasPathSum returned: FALSE

Enter sum: sum: 4
treeHasPathSum returned: FALSE

Enter sum: sum: 5
treeHasPathSum returned: TRUE

Enter sum: sum: 6
treeHasPathSum returned: TRUE

Enter sum: sum: 7
treeHasPathSum returned: TRUE

Enter sum: sum: 8
treeHasPathSum returned: FALSE

Enter sum: sum: 9
treeHasPathSum returned: FALSE

Enter sum: sum: 10
treeHasPathSum returned: FALSE

Enter sum: sum: 11
treeHasPathSum returned: FALSE

Enter sum: sum: 12
treeHasPathSum returned: TRUE

Enter sum: sum: 13
treeHasPathSum returned: FALSE

Enter sum: sum: 14
treeHasPathSum returned: FALSE

Enter sum: sum: 15
treeHasPathSum returned: FALSE

Enter sum: 